---
global:
  tolerations:
    - key: "components.gke.io/gke-managed-components"
      operator: Equal
      value: "true"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "blockapt-dev-external-secrets@blockapt-dev-72311d19.iam.gserviceaccount.com"  # From Terraform output

resources:
  limits:
    cpu: 50m
    memory: 64Mi

webhook:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi

certController:
  resources:
    limits:
        cpu: 50m
        memory: 128Mi
