component: search-logger

image:
  repository: search

# node: user node uid=gid=1000
container:
  env:
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: mongodb-icyber-logger-db-search
          key: "connectionString.standard"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000

pod:
  securityContext:
    fsGroup: 1000

serviceAccount:
  extraSecrets:
    - name: mongodb-icyber-logger-db-search

# Nothing to expose
ports: null
service:
  enabled: false
