## Fetch user passwords from Google Secret Manager
# Default admin
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-admin
  namespace: blockapt
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecretStore.kind | quote }}
    name: {{ .Values.externalSecretStore.name | quote }}
  target:
    name: es-mongodb-admin
  data:
  - secretKey: password
    remoteRef:
      key: mongodb-admin
# Loop over application users
{{- range .Values.blockAPT.users }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-{{ . }}
  namespace: blockapt
spec:
  secretStoreRef:
    kind: {{ $.Values.externalSecretStore.kind | quote }}
    name: {{ $.Values.externalSecretStore.name | quote }}
  target:
    name: es-mongodb-{{ . }}
  data:
  - secretKey: password
    remoteRef:
      key: mongodb-{{ . }}
{{- end }}
