---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      # Stick 1.13.x to support Gateway CRDs v1beta1 automatically installed in GKE 1.27.x
      # https://github.com/cert-manager/cert-manager/issues/6649
      targetRevision: 1.13.5
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/deploy/marketplace/values/cert-manager.yaml
    - ref: values
      repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
      targetRevision: "main"
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
