---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-mp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    gcpsm:
      # Google Secret Manager (marketplace)
      projectID: v7labs-public-6fa79b13
      auth:
        workloadIdentity:
          # GKE (marketplace)
          clusterLocation: europe-west1
          clusterName: v7labs-mp-euw1
          clusterProjectID: v7labs-public-6fa79b13
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
