---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jwt
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
      targetRevision: "main"
      path: deploy/charts/blockapt
      helm:
        releaseName: jwt
        valueFiles:
          - $values/deploy/marketplace/values/jwt.yaml
    - ref: values
      repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
      targetRevision: "main"
  destination:
    namespace: marketplace
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
