{{- if .Values.configMap.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- . | nindent 2 }}
  {{- end }}
{{- end }}
