{{- if .Values.externalEnvironmentSecrets.secretKeys }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "common.fullname" . }}-externalsecretmap
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.externalEnvironmentSecrets.refreshInterval }}
  refreshInterval: {{ int . }}
  {{- end }}
  secretStoreRef:
    kind: {{ .Values.externalEnvironmentSecrets.secretStoreRef.kind  | quote }}
    name: {{ .Values.externalEnvironmentSecrets.secretStoreRef.name  | quote }}
  target:
    name: {{ template "common.fullname" . }}-externalsecretmap
    {{- with .Values.externalEnvironmentSecrets.target }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  data:
  {{- range .Values.externalEnvironmentSecrets.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalEnvironmentSecrets.prefix }}{{ . }}
  {{- end }}
{{- end }}
