{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "common.fullname" . }}
  {{- with .Values.gateway.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.gateway.className }}
  gatewayClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.gateway.addresses }}
  addresses: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.listeners }}
  listeners: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
