{{- if and .Values.metrics.enabled .Values.metrics.podMonitoring.enabled }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ template "common.fullname" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.podMonitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      {{- with .Values.metrics.podMonitoring.endpoint.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.podMonitoring.endpoint.metricRelabeling }}
      metricRelabeling: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitoring.endpoint.timeout }}
      timeout: {{ . }}
      {{- end }}
  {{- with .Values.metrics.podMonitoring.limits }}
  limits: {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
  {{- with .Values.metrics.podMonitoring.targetLabels }}
  targetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
