{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  annotations:
    {{- if .Values.service.neg }}
    cloud.google.com/neg: '{"exposed_ports":{"{{ int .Values.service.ports.http }}":{}}}'
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ int .Values.service.ports.http }}
      targetPort: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ int .Values.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
