{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" . }}
  annotations:
    {{- with .Values.serviceAccount.enforceMountableSecrets }}
    kubernetes.io/enforce-mountable-secrets: "true"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
secrets:
  {{- with .Values.image.pullSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.externalEnvironmentSecrets.secretKeys }}
  - name: {{ template "common.fullname" . }}-externalsecretmap
  {{- end }}
  {{- with .Values.serviceAccount.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
