---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deploy/marketplace/manifests
    repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
    targetRevision: "main"
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
