---
bases:
  - environments.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  # https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.14.7
    values:
      - ../blockapt/values/{{ .Environment.Name }}/cert-manager.yaml
    labels:
      component: tls
