---
bases:
  - environments.yaml

repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io

releases:
  # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
  # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 0.9.20
    values:
      - ../blockapt/values/{{ .Environment.Name }}/cert-manager.yaml
    labels:
      component: secrets
