---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.6
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/deploy/blockapt/values/dev/cert-manager.yaml
    - ref: values
      repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
      targetRevision: "main"
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
