---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.9.19
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/deploy/blockapt/values/dev/external-secrets.yaml
    - ref: values
      repoURL: "git@github.com:zencore-dev/blockapt-infra.git"
      targetRevision: "main"
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
