---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ddumas@zencore.dev
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "blockapt.immersion.dev"  # From Terraform output
      dns01:
        cloudDNS:
          project: "blockapt-dev-72311d19"  # From Terraform output
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ddumas@zencore.dev
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "blockapt.immersion.dev"  # From Terraform output
      dns01:
        cloudDNS:
          project: "blockapt-dev-72311d19"  # From Terraform output
