---
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "v7labs-mp-external-secrets@v7labs-public-6fa79b13.iam.gserviceaccount.com"

resources:
  limits:
    cpu: 250m
    memory: 512Mi

webhook:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi

certController:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
